kind: Service
apiVersion: v1
metadata:
  name: books-service
spec:
  type: NodePort
  selector:
    app: books-app
  ports:
  - name: books-service
    protocol: TCP
    port: 80
    targetPort: 8080
